# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MEEGA_liveValuesWidget.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QSizePolicy,
    QWidget)

class Ui_LiveValuesWidget(object):
    def setupUi(self, LiveValuesWidget):
        if not LiveValuesWidget.objectName():
            LiveValuesWidget.setObjectName(u"LiveValuesWidget")
        LiveValuesWidget.resize(450, 650)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LiveValuesWidget.sizePolicy().hasHeightForWidth())
        LiveValuesWidget.setSizePolicy(sizePolicy)
        LiveValuesWidget.setMinimumSize(QSize(450, 650))
        LiveValuesWidget.setMaximumSize(QSize(450, 650))
        self.frame = QFrame(LiveValuesWidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 130, 61, 16))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(3)
        self.nozzlePressure2 = QLabel(self.frame)
        self.nozzlePressure2.setObjectName(u"nozzlePressure2")
        self.nozzlePressure2.setGeometry(QRect(0, 0, 51, 16))
        self.nozzlePressure2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_2 = QFrame(LiveValuesWidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 150, 61, 16))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(3)
        self.nozzlePressure1 = QLabel(self.frame_2)
        self.nozzlePressure1.setObjectName(u"nozzlePressure1")
        self.nozzlePressure1.setGeometry(QRect(0, 0, 51, 16))
        self.nozzlePressure1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_3 = QFrame(LiveValuesWidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(380, 110, 41, 16))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(3)
        self.nozzleTemperature3 = QLabel(self.frame_3)
        self.nozzleTemperature3.setObjectName(u"nozzleTemperature3")
        self.nozzleTemperature3.setGeometry(QRect(0, 0, 37, 12))
        self.nozzleTemperature3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_4 = QFrame(LiveValuesWidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 110, 61, 16))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_4.setLineWidth(3)
        self.nozzlePressure3 = QLabel(self.frame_4)
        self.nozzlePressure3.setObjectName(u"nozzlePressure3")
        self.nozzlePressure3.setGeometry(QRect(0, 0, 51, 16))
        self.nozzlePressure3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_5 = QFrame(LiveValuesWidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(60, 250, 61, 16))
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_5.setLineWidth(3)
        self.chamberPressure = QLabel(self.frame_5)
        self.chamberPressure.setObjectName(u"chamberPressure")
        self.chamberPressure.setGeometry(QRect(0, 0, 51, 16))
        self.chamberPressure.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_6 = QFrame(LiveValuesWidget)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(270, 330, 61, 16))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_6.setLineWidth(3)
        self.accumulatorPressure = QLabel(self.frame_6)
        self.accumulatorPressure.setObjectName(u"accumulatorPressure")
        self.accumulatorPressure.setGeometry(QRect(0, 0, 51, 16))
        self.accumulatorPressure.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_7 = QFrame(LiveValuesWidget)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(40, 570, 41, 16))
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_7.setLineWidth(3)
        self.accumulatorTemperature = QLabel(self.frame_7)
        self.accumulatorTemperature.setObjectName(u"accumulatorTemperature")
        self.accumulatorTemperature.setGeometry(QRect(0, 0, 37, 12))
        self.accumulatorTemperature.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_8 = QFrame(LiveValuesWidget)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(380, 130, 41, 16))
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_8.setLineWidth(3)
        self.nozzleTemperature2 = QLabel(self.frame_8)
        self.nozzleTemperature2.setObjectName(u"nozzleTemperature2")
        self.nozzleTemperature2.setGeometry(QRect(0, 0, 37, 12))
        self.nozzleTemperature2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_9 = QFrame(LiveValuesWidget)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(380, 150, 41, 16))
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_9.setLineWidth(3)
        self.nozzleTemperature1 = QLabel(self.frame_9)
        self.nozzleTemperature1.setObjectName(u"nozzleTemperature1")
        self.nozzleTemperature1.setGeometry(QRect(0, 0, 37, 12))
        self.nozzleTemperature1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_10 = QFrame(LiveValuesWidget)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(360, 250, 41, 16))
        self.frame_10.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_10.setLineWidth(3)
        self.chamberTemperature = QLabel(self.frame_10)
        self.chamberTemperature.setObjectName(u"chamberTemperature")
        self.chamberTemperature.setGeometry(QRect(0, 0, 37, 12))
        self.chamberTemperature.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label = QLabel(LiveValuesWidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(330, 480, 81, 16))
        self.frame_11 = QFrame(LiveValuesWidget)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(330, 500, 61, 16))
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_11.setLineWidth(3)
        self.coldJunctionTemperature = QLabel(self.frame_11)
        self.coldJunctionTemperature.setObjectName(u"coldJunctionTemperature")
        self.coldJunctionTemperature.setGeometry(QRect(0, 0, 51, 16))
        self.coldJunctionTemperature.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_12 = QFrame(LiveValuesWidget)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(330, 450, 61, 16))
        self.frame_12.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_12.setLineWidth(3)
        self.ambientPressure = QLabel(self.frame_12)
        self.ambientPressure.setObjectName(u"ambientPressure")
        self.ambientPressure.setGeometry(QRect(0, 0, 51, 16))
        self.ambientPressure.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QLabel(LiveValuesWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(330, 430, 61, 16))

        self.retranslateUi(LiveValuesWidget)

        QMetaObject.connectSlotsByName(LiveValuesWidget)
    # setupUi

    def retranslateUi(self, LiveValuesWidget):
        LiveValuesWidget.setWindowTitle(QCoreApplication.translate("LiveValuesWidget", u"Live Values Widget", None))
        self.nozzlePressure2.setText(QCoreApplication.translate("LiveValuesWidget", u"0 Pa", None))
        self.nozzlePressure1.setText(QCoreApplication.translate("LiveValuesWidget", u"0 Pa", None))
        self.nozzleTemperature3.setText(QCoreApplication.translate("LiveValuesWidget", u"0 K", None))
        self.nozzlePressure3.setText(QCoreApplication.translate("LiveValuesWidget", u"0 Pa", None))
        self.chamberPressure.setText(QCoreApplication.translate("LiveValuesWidget", u"0 Pa", None))
        self.accumulatorPressure.setText(QCoreApplication.translate("LiveValuesWidget", u"0 Pa", None))
        self.accumulatorTemperature.setText(QCoreApplication.translate("LiveValuesWidget", u"0 K", None))
        self.nozzleTemperature2.setText(QCoreApplication.translate("LiveValuesWidget", u"0 K", None))
        self.nozzleTemperature1.setText(QCoreApplication.translate("LiveValuesWidget", u"0 K", None))
        self.chamberTemperature.setText(QCoreApplication.translate("LiveValuesWidget", u"0 K", None))
        self.label.setText(QCoreApplication.translate("LiveValuesWidget", u"Cold Junction:", None))
        self.coldJunctionTemperature.setText(QCoreApplication.translate("LiveValuesWidget", u"0 K", None))
        self.ambientPressure.setText(QCoreApplication.translate("LiveValuesWidget", u"0 Pa", None))
        self.label_3.setText(QCoreApplication.translate("LiveValuesWidget", u"Ambient:", None))
    # retranslateUi

