pyside6-uic UI-Files\MEEGA_mainWindow.ui -o MEEGA_mainWindow.py
pyside6-uic UI-Files\MEEGA_connection.ui -o MEEGA_connection.py
pyside6-uic UI-Files\MEEGA_time.ui -o MEEGA_time.py
pyside6-uic UI-Files\MEEGA_results.ui -o MEEGA_results.py
pyside6-uic UI-Files\MEEGA_documentation.ui -o MEEGA_documentation.py
pyside6-uic UI-Files\MEEGA_startup.ui -o MEEGA_startup.py
pyside6-uic UI-Files\MEEGA_error.ui -o MEEGA_error.py
pyside6-uic UI-Files\MEEGA_controlPanel.ui -o MEEGA_controlPanel.py
pyside6-uic UI-Files\MEEGA_calibration.ui -o MEEGA_calibration.py
pyside6-uic UI-Files\MEEGA_diagramSettings.ui -o MEEGA_diagramSettings.py
pyside6-uic UI-Files\MEEGA_export.ui -o MEEGA_export.py
pyside6-rcc UI-Files\resources.qrc -o resources_rc.py