# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MEEGA_mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QFrame,
    QGraphicsView, QGridLayout, QHBoxLayout, QLabel,
    QLayout, QListView, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QSpacerItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.resize(1920, 1080)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.Germany))
        MainWindow.setAnimated(False)
        self.actionYou_Cant_Help_Me = QAction(MainWindow)
        self.actionYou_Cant_Help_Me.setObjectName(u"actionYou_Cant_Help_Me")
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionDeutsch = QAction(MainWindow)
        self.actionDeutsch.setObjectName(u"actionDeutsch")
        self.actionTesting = QAction(MainWindow)
        self.actionTesting.setObjectName(u"actionTesting")
        self.actionRecording = QAction(MainWindow)
        self.actionRecording.setObjectName(u"actionRecording")
        self.actionReplaying = QAction(MainWindow)
        self.actionReplaying.setObjectName(u"actionReplaying")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionResults = QAction(MainWindow)
        self.actionResults.setObjectName(u"actionResults")
        self.actionRetry = QAction(MainWindow)
        self.actionRetry.setObjectName(u"actionRetry")
        self.actionConnect = QAction(MainWindow)
        self.actionConnect.setObjectName(u"actionConnect")
#if QT_CONFIG(shortcut)
        self.actionConnect.setShortcut(u"F8")
#endif // QT_CONFIG(shortcut)
        self.actionDisconnect = QAction(MainWindow)
        self.actionDisconnect.setObjectName(u"actionDisconnect")
        self.actionStart = QAction(MainWindow)
        self.actionStart.setObjectName(u"actionStart")
        self.actionTroubleshoot = QAction(MainWindow)
        self.actionTroubleshoot.setObjectName(u"actionTroubleshoot")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionAutomatic = QAction(MainWindow)
        self.actionAutomatic.setObjectName(u"actionAutomatic")
        self.actionManual = QAction(MainWindow)
        self.actionManual.setObjectName(u"actionManual")
        self.actionAutomatic_2 = QAction(MainWindow)
        self.actionAutomatic_2.setObjectName(u"actionAutomatic_2")
        self.actionManual_2 = QAction(MainWindow)
        self.actionManual_2.setObjectName(u"actionManual_2")
        self.actionEnglish_2 = QAction(MainWindow)
        self.actionEnglish_2.setObjectName(u"actionEnglish_2")
        self.actionDeutsch_2 = QAction(MainWindow)
        self.actionDeutsch_2.setObjectName(u"actionDeutsch_2")
        self.actionHousholding = QAction(MainWindow)
        self.actionHousholding.setObjectName(u"actionHousholding")
        self.actionMeasurements = QAction(MainWindow)
        self.actionMeasurements.setObjectName(u"actionMeasurements")
        self.actionEverything = QAction(MainWindow)
        self.actionEverything.setObjectName(u"actionEverything")
        self.actionRecording_2 = QAction(MainWindow)
        self.actionRecording_2.setObjectName(u"actionRecording_2")
        self.actionReplying = QAction(MainWindow)
        self.actionReplying.setObjectName(u"actionReplying")
        self.actionTesting_2 = QAction(MainWindow)
        self.actionTesting_2.setObjectName(u"actionTesting_2")
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.connectionFrame = QFrame(self.centralwidget)
        self.connectionFrame.setObjectName(u"connectionFrame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.connectionFrame.sizePolicy().hasHeightForWidth())
        self.connectionFrame.setSizePolicy(sizePolicy)
        self.connectionFrame.setMinimumSize(QSize(250, 70))
        self.connectionFrame.setBaseSize(QSize(0, 0))
        self.connectionFrame.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.connectionFrame.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.connectionFrame.setFrameShape(QFrame.Shape.Box)
        self.connectionFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.horizontalLayout_3 = QHBoxLayout(self.connectionFrame)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.label_5 = QLabel(self.connectionFrame)
        self.label_5.setObjectName(u"label_5")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setMinimumSize(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(20)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        self.label_5.setFont(font1)
        self.label_5.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)

        self.horizontalLayout_3.addWidget(self.label_5)

        self.frame_6 = QFrame(self.connectionFrame)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy2)
        self.frame_6.setMinimumSize(QSize(50, 50))
        self.frame_6.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)

        self.horizontalLayout_3.addWidget(self.frame_6)


        self.horizontalLayout_6.addWidget(self.connectionFrame)

        self.horizontalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_2)

        self.frame_7 = QFrame(self.centralwidget)
        self.frame_7.setObjectName(u"frame_7")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy3)
        self.frame_7.setMinimumSize(QSize(166, 0))
        self.frame_7.setFrameShape(QFrame.Shape.Box)
        self.frame_7.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_7.setLineWidth(1)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.label_14 = QLabel(self.frame_7)
        self.label_14.setObjectName(u"label_14")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy4)
        self.label_14.setMinimumSize(QSize(66, 0))
        self.label_14.setFont(font1)

        self.horizontalLayout_5.addWidget(self.label_14)

        self.horizontalSpacer_6 = QSpacerItem(10, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_6)

        self.label_13 = QLabel(self.frame_7)
        self.label_13.setObjectName(u"label_13")
        sizePolicy4.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy4)
        self.label_13.setMinimumSize(QSize(66, 0))
        self.label_13.setFont(font1)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_5.addWidget(self.label_13)


        self.horizontalLayout_6.addWidget(self.frame_7)

        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)

        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.distancePlotFrame = QFrame(self.centralwidget)
        self.distancePlotFrame.setObjectName(u"distancePlotFrame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(10)
        sizePolicy5.setHeightForWidth(self.distancePlotFrame.sizePolicy().hasHeightForWidth())
        self.distancePlotFrame.setSizePolicy(sizePolicy5)
        self.distancePlotFrame.setMinimumSize(QSize(250, 0))
        self.distancePlotFrame.setMaximumSize(QSize(16777215, 16777215))
        self.distancePlotFrame.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.distancePlotFrame.setFrameShape(QFrame.Shape.Box)
        self.distancePlotFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.label_8 = QLabel(self.distancePlotFrame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 60, 121, 16))
        self.label_8.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.verticalLayout.addWidget(self.distancePlotFrame)


        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy6)
        self.frame_5.setMinimumSize(QSize(100, 0))
        self.frame_5.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.frame_5.setFrameShape(QFrame.Shape.Box)
        self.frame_5.setFrameShadow(QFrame.Shadow.Plain)
        self.label_7 = QLabel(self.frame_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 30, 81, 16))
        self.label_7.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.horizontalLayout_2.addWidget(self.frame_5)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, 0)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        sizePolicy2.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy2)
        self.graphicsView.setMinimumSize(QSize(0, 0))
        self.graphicsView.setMaximumSize(QSize(200, 200))

        self.verticalLayout_3.addWidget(self.graphicsView)

        self.verticalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)

        self.verticalLayout_3.addItem(self.verticalSpacer_2)

        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy7)
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_12)


        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.horizontalLayout_2.setStretch(0, 1)

        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy8.setHorizontalStretch(1)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy8)
        self.frame_2.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.verticalLayout_7 = QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.listView = QListView(self.frame_2)
        self.listView.setObjectName(u"listView")
        self.listView.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.listView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listView.setItemAlignment(Qt.AlignmentFlag.AlignLeading)

        self.verticalLayout_7.addWidget(self.listView)


        self.horizontalLayout_4.addWidget(self.frame_2)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy9.setHorizontalStretch(3)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy9)
        self.frame.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(70, 50, 101, 16))
        self.label_9.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.horizontalLayout_4.addWidget(self.frame)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy10.setHorizontalStretch(1)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy10)
        self.frame_3.setMinimumSize(QSize(0, 130))
        self.frame_3.setSizeIncrement(QSize(0, 0))
        self.frame_3.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.frame_3.setFrameShape(QFrame.Shape.Box)
        self.frame_3.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_3.setLineWidth(1)
        self.verticalLayout_5 = QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.pushButton = QPushButton(self.frame_3)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy11.setHorizontalStretch(1)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy11)
        self.pushButton.setMinimumSize(QSize(50, 50))
        self.pushButton.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton)

        self.pushButton_2 = QPushButton(self.frame_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        sizePolicy11.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy11)
        self.pushButton_2.setMinimumSize(QSize(50, 50))
        self.pushButton_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_2.setBaseSize(QSize(0, 0))
        self.pushButton_2.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.verticalLayout_5.addWidget(self.pushButton_2)


        self.verticalLayout_4.addWidget(self.frame_3)

        self.verticalSpacer = QSpacerItem(20, 50, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)

        self.verticalLayout_4.addItem(self.verticalSpacer)

        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy10.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy10)
        self.frame_4.setMinimumSize(QSize(0, 130))
        self.frame_4.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.frame_4.setFrameShape(QFrame.Shape.Box)
        self.frame_4.setFrameShadow(QFrame.Shadow.Plain)
        self.verticalLayout_6 = QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.pushButton_3 = QPushButton(self.frame_4)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy11.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy11)
        self.pushButton_3.setMinimumSize(QSize(50, 50))
        self.pushButton_3.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.verticalLayout_6.addWidget(self.pushButton_3)

        self.pushButton_4 = QPushButton(self.frame_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        sizePolicy11.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy11)
        self.pushButton_4.setMinimumSize(QSize(50, 50))
        self.pushButton_4.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.verticalLayout_6.addWidget(self.pushButton_4)


        self.verticalLayout_4.addWidget(self.frame_4)


        self.horizontalLayout_4.addLayout(self.verticalLayout_4)


        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)

        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        sizePolicy12 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy12.setHorizontalStretch(0)
        sizePolicy12.setVerticalStretch(0)
        sizePolicy12.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy12)
        self.label_2.setMinimumSize(QSize(127, 0))
        self.label_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_2.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_4, 0, 7, 1, 1)

        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        sizePolicy4.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy4)
        self.label_6.setMinimumSize(QSize(97, 0))
        self.label_6.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_6, 1, 8, 1, 1)

        self.progressBar_3 = QProgressBar(self.centralwidget)
        self.progressBar_3.setObjectName(u"progressBar_3")
        sizePolicy13 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy13.setHorizontalStretch(1)
        sizePolicy13.setVerticalStretch(0)
        sizePolicy13.setHeightForWidth(self.progressBar_3.sizePolicy().hasHeightForWidth())
        self.progressBar_3.setSizePolicy(sizePolicy13)
        self.progressBar_3.setMinimumSize(QSize(50, 0))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(12)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        self.progressBar_3.setFont(font2)
        self.progressBar_3.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.progressBar_3.setMinimum(0)
        self.progressBar_3.setValue(100)
        self.progressBar_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.progressBar_3, 0, 4, 1, 1)

        self.progressBar_5 = QProgressBar(self.centralwidget)
        self.progressBar_5.setObjectName(u"progressBar_5")
        sizePolicy13.setHeightForWidth(self.progressBar_5.sizePolicy().hasHeightForWidth())
        self.progressBar_5.setSizePolicy(sizePolicy13)
        self.progressBar_5.setMinimumSize(QSize(50, 0))
        self.progressBar_5.setFont(font2)
        self.progressBar_5.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.progressBar_5.setValue(100)
        self.progressBar_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.progressBar_5, 0, 0, 1, 1)

        self.progressBar_2 = QProgressBar(self.centralwidget)
        self.progressBar_2.setObjectName(u"progressBar_2")
        sizePolicy13.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy13)
        self.progressBar_2.setMinimumSize(QSize(50, 0))
        self.progressBar_2.setFont(font2)
        self.progressBar_2.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.progressBar_2.setValue(100)
        self.progressBar_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.progressBar_2, 0, 2, 1, 1)

        self.horizontalSpacer_3 = QSpacerItem(20, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_3, 0, 3, 1, 1)

        self.horizontalSpacer = QSpacerItem(20, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 0, 5, 1, 1)

        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        sizePolicy14 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy14.setHorizontalStretch(0)
        sizePolicy14.setVerticalStretch(0)
        sizePolicy14.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy14)
        self.label.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        sizePolicy15 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy15.setHorizontalStretch(0)
        sizePolicy15.setVerticalStretch(0)
        sizePolicy15.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy15)
        self.label_3.setLocale(QLocale(QLocale.English, QLocale.Germany))

        self.horizontalLayout.addWidget(self.label_3)

        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        sizePolicy14.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy14)
        self.label_4.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.label_4)


        self.gridLayout.addLayout(self.horizontalLayout, 1, 6, 1, 1)

        self.progressBar_4 = QProgressBar(self.centralwidget)
        self.progressBar_4.setObjectName(u"progressBar_4")
        sizePolicy13.setHeightForWidth(self.progressBar_4.sizePolicy().hasHeightForWidth())
        self.progressBar_4.setSizePolicy(sizePolicy13)
        self.progressBar_4.setMinimumSize(QSize(97, 0))
        self.progressBar_4.setBaseSize(QSize(97, 0))
        self.progressBar_4.setFont(font2)
        self.progressBar_4.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.progressBar_4.setValue(100)
        self.progressBar_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.progressBar_4, 0, 8, 1, 1)

        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        sizePolicy16 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy16.setHorizontalStretch(10)
        sizePolicy16.setVerticalStretch(0)
        sizePolicy16.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy16)
        self.progressBar.setMinimumSize(QSize(100, 0))
        self.progressBar.setFont(font2)
        self.progressBar.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.progressBar.setValue(24)
        self.progressBar.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.progressBar, 0, 6, 1, 1)

        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        sizePolicy14.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy14)
        self.label_11.setLocale(QLocale(QLocale.English, QLocale.Germany))
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)

        self.horizontalSpacer_5 = QSpacerItem(20, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_5, 0, 1, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)

        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QRect(0, 0, 1920, 20))
        self.menubar.setFont(font)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setFont(font)
        self.menuExport = QMenu(self.menuFile)
        self.menuExport.setObjectName(u"menuExport")
        self.menuMode = QMenu(self.menuFile)
        self.menuMode.setObjectName(u"menuMode")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuConnection = QMenu(self.menubar)
        self.menuConnection.setObjectName(u"menuConnection")
        self.menuMode_2 = QMenu(self.menuConnection)
        self.menuMode_2.setObjectName(u"menuMode_2")
        self.menuLanguage = QMenu(self.menubar)
        self.menuLanguage.setObjectName(u"menuLanguage")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnection.menuAction())
        self.menubar.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionResults)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuMode.menuAction())
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionQuit)
        self.menuExport.addAction(self.actionHousholding)
        self.menuExport.addAction(self.actionMeasurements)
        self.menuExport.addAction(self.actionEverything)
        self.menuMode.addAction(self.actionRecording_2)
        self.menuMode.addAction(self.actionReplying)
        self.menuMode.addAction(self.actionTesting_2)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuConnection.addAction(self.actionConnect)
        self.menuConnection.addSeparator()
        self.menuConnection.addAction(self.actionRetry)
        self.menuConnection.addSeparator()
        self.menuConnection.addAction(self.actionTroubleshoot)
        self.menuConnection.addAction(self.menuMode_2.menuAction())
        self.menuConnection.addSeparator()
        self.menuConnection.addAction(self.actionDisconnect)
        self.menuMode_2.addAction(self.actionAutomatic_2)
        self.menuMode_2.addAction(self.actionManual_2)
        self.menuLanguage.addAction(self.actionEnglish_2)
        self.menuLanguage.addAction(self.actionDeutsch_2)

        self.retranslateUi(MainWindow)

        self.pushButton.setDefault(True)
        self.pushButton_3.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MEEGA - Ground Station", None))
        self.actionYou_Cant_Help_Me.setText(QCoreApplication.translate("MainWindow", u"You Cant Help Me", None))
#if QT_CONFIG(shortcut)
        self.actionYou_Cant_Help_Me.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionDeutsch.setText(QCoreApplication.translate("MainWindow", u"Deutsch", None))
        self.actionTesting.setText(QCoreApplication.translate("MainWindow", u"Testing", None))
        self.actionRecording.setText(QCoreApplication.translate("MainWindow", u"Recording", None))
        self.actionReplaying.setText(QCoreApplication.translate("MainWindow", u"Replaying", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionResults.setText(QCoreApplication.translate("MainWindow", u"Results", None))
#if QT_CONFIG(shortcut)
        self.actionResults.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionRetry.setText(QCoreApplication.translate("MainWindow", u"Reconnect", None))
#if QT_CONFIG(shortcut)
        self.actionRetry.setShortcut(QCoreApplication.translate("MainWindow", u"F9", None))
#endif // QT_CONFIG(shortcut)
        self.actionConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.actionDisconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.actionStart.setText(QCoreApplication.translate("MainWindow", u"Restart", None))
        self.actionTroubleshoot.setText(QCoreApplication.translate("MainWindow", u"Connection Log", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.actionAutomatic.setText(QCoreApplication.translate("MainWindow", u"Automatic", None))
        self.actionManual.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.actionAutomatic_2.setText(QCoreApplication.translate("MainWindow", u"Automatic", None))
        self.actionManual_2.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.actionEnglish_2.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionDeutsch_2.setText(QCoreApplication.translate("MainWindow", u"Deutsch", None))
        self.actionHousholding.setText(QCoreApplication.translate("MainWindow", u"Housholding", None))
        self.actionMeasurements.setText(QCoreApplication.translate("MainWindow", u"Measurements", None))
        self.actionEverything.setText(QCoreApplication.translate("MainWindow", u"Full Dataset", None))
        self.actionRecording_2.setText(QCoreApplication.translate("MainWindow", u"Recording", None))
        self.actionReplying.setText(QCoreApplication.translate("MainWindow", u"Replaying", None))
        self.actionTesting_2.setText(QCoreApplication.translate("MainWindow", u"Testing", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindow", u"Documentation", None))
#if QT_CONFIG(shortcut)
        self.actionDocumentation.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Graph over Distance", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"System Status", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Recording", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Graph over Time", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Mean", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Last", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Total", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Start of Data Storage", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Shutdown", None))
        self.progressBar_3.setFormat(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.progressBar_5.setFormat("")
        self.progressBar_2.setFormat(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Lift Off", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Start of Experiment", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"End of Experiment", None))
        self.progressBar_4.setFormat(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.progressBar.setFormat(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Pre-Flight", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"Export", None))
        self.menuMode.setTitle(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuConnection.setTitle(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.menuMode_2.setTitle(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
    # retranslateUi

